#!/usr/bin/env tsx
/**
 * Seed production seo_priority cities — no file argument needed.
 *
 * After a new publish adds the seo_priority column (DEFAULT false), run this
 * script with the production DATABASE_URL to mark the correct 1,560 cities.
 *
 * Usage:
 *   cd scripts && DATABASE_URL=<prod-url> npx tsx src/seed-priority-cities.ts
 *
 * Safe to re-run (idempotent — only sets seo_priority=true, never clears it).
 *
 * Verification: after the UPDATE, the script confirms each of the 1,560 expected
 * slugs is present in the DB and exits with code 1 if any are missing.
 *
 * Slugs extracted from district master XLSX (2026-08-08).
 * Total: 1,560 priority cities (1,149 district-matched + 741 original list, union).
 */

import { Client } from "pg";

const PRIORITY_SLUGS: string[] = [
  "adoni-town-so-andhra-pradesh","amalapuram-andhra-pradesh","anakapalle-ho-andhra-pradesh","anantapur-ho-andhra-pradesh",
  "aurangabad-andhra-pradesh","bapatla-ho-andhra-pradesh","bhimavaram-andhra-pradesh","chilakaluripet-so-andhra-pradesh",
  "chirala-bazar-so-andhra-pradesh","chittoor-sugarfactory-andhra-pradesh","dharmapuri-andhra-pradesh","dharmavaram-andhra-pradesh",
  "eastpalem-andhra-pradesh","ganapavaram","gandhinagar-andhra-pradesh","gudivada-andhra-pradesh",
  "guntakal-market-so-andhra-pradesh","guntur-collectorate-so-andhra-pradesh","hindupur-extns-so-andhra-pradesh","jammu-andhra-pradesh",
  "kadapanatham-andhra-pradesh","kadiripulikunta-andhra-pradesh","kakinada-bazar-so-andhra-pradesh","karur-andhra-pradesh",
  "kavali-ho-andhra-pradesh","kota-andhra-pradesh","krishnagiri-andhra-pradesh","krishnavaram-andhra-pradesh",
  "kurnool-road-o-so-andhra-pradesh","machilipatnam-ho-andhra-pradesh","madanapalle-ho-andhra-pradesh","mangalagiri-ho-andhra-pradesh",
  "mohammadabad-andhra-pradesh","nandyal-ho-andhra-pradesh","narasapuram-andhra-pradesh","narasaraopet-ho-andhra-pradesh",
  "nellore-ho-andhra-pradesh","ongole-ho-andhra-pradesh","prakasam-bhavan-so-andhra-pradesh","proddatur-fort-so-andhra-pradesh",
  "rajam-andhra-pradesh","rayachoti-so-andhra-pradesh","srikakulam-andhra-pradesh","srinagar-andhra-pradesh",
  "tadepalle-andhra-pradesh","taduvai","tanuku-ho-andhra-pradesh","tenali-ho-andhra-pradesh",
  "tirupati-uth-so-andhra-pradesh","tunivada-andhra-pradesh","ukkunagaram-so-andhra-pradesh","vijayawada-gpo-andhra-pradesh",
  "visakhapatnam-ho-andhra-pradesh","vizianagaram-ho-andhra-pradesh","west-varathur-andhra-pradesh","abhayapuri-so-assam",
  "amarpur-assam","azara-so-assam","badarpur-so-karimganj-assam","bangaon-assam",
  "barpeta-ho-assam","bilasipara-so-assam","bilaspur-assam","biswanathghat-so-assam",
  "bongaigaon-so-assam","bori-assam","chandpur-assam","chandrapur-assam",
  "darrang-panbari-so-assam","dhekiajuli-so-assam","dhemaji-so-assam","dhubri-ho-assam",
  "dhupguri-assam","dibai-assam","dibrugarh-ho-assam","diphu-ho-assam",
  "duliajan-so-assam","gandhinagar-assam","goalpara-head-post-office-assam","golaghat-ho-assam",
  "goroimari-assam","guwahati-gpo-assam","haflong-ptc-so-assam","hailakandi-ho-assam",
  "hamren-so-assam","hojai-so-assam","islampur-assam","jangalpara-assam",
  "jorhat-ho-assam","kajalgaon-so-assam","kalgachia-so-assam","kalyanpur-assam",
  "kamarkuchi-so-assam","kharupetiaghat-so-assam","kokrajhar-bagicha-assam","lakhimpur-assam",
  "lanka-so-nagaon-assam","lumding-bazar-assam","madhupur-assam","majulibongaon-so-assam",
  "mangaldoi-ho-assam","mankachar-so-assam","mirzapur-assam","moirabari-so-assam",
  "morigaon-so-assam","nagaon-assam","nalbari-bo-assam","north-lakhimpur-ho-assam",
  "pratapgarh-assam","raipur-assam","rampur-assam","saidpur-assam",
  "samaguri-bazar-assam","silchar-court-so-assam","siliguri-assam","singri-assam",
  "srinagar-assam","tezpur-medical-college-so-assam","tinsukia-juria-assam","udalguri-so-assam",
  "akbarpur-bihar","alauli-so-bihar","amarpur-bo-bihar","araria-bihar",
  "areraj-bihar","arraha-bo-bihar","arwal-so-bihar","asarganj-bihar",
  "atri-bihar","aura-bihar","bagaha-bihar","bahadurpur-bo-bihar",
  "bairgania-bihar","baisi-bihar","bakhri-dua-bo-bihar","bakhtiyarpur-so-bihar",
  "balia-bo-bihar","banjari-bihar","banka-ho-bihar","bansi-bihar",
  "barbigha-bihar","barharia-bo-bihar","barhiya-bihar","bari-bihar",
  "begusarai-court-bihar","belsand-bihar","benipur-bihar","bettiah-rs-bihar",
  "bhabua-bihar","bhagalpur-devgaon-bo-bihar","bhaptiyahi-bazar-bihar","bhojpur-bo-bihar",
  "bhore-bihar","bihari-bigha-bo-bihar","bihpur-bihar","bihta-bo-bihar",
  "bikramganj-bihar","birpur-bo-bihar","buxar-jail-bihar","chausa-madhepura-bihar",
  "chhapra-bahas-bo-bihar","chirand-bo-bihar","darauli-bihar","darbhanga-bara-bazar-bihar",
  "daudnagar-bihar","dehri-r-s-bihar","dhaka-bihar","dighari-bo-bihar",
  "dighwara-bihar","ekma-bihar","fatehpur-bihar","fatwa-bihar",
  "forbesganj-bihar","gaighat-bo-bihar","gaya-jail-bihar","gopalganj-college-bihar",
  "hajipur-chowk-bihar","jaipur-bihar","jamui-bo-bihar","jehanabad-ho-bihar",
  "jhanjharpur-bihar","jogapatti-bihar","jokihat-bihar","kahalgaon-bihar",
  "kalyanpur-bihar","katihar-mill-bihar","khagaria-mukhya-dakghar-bihar","khajauli-bihar",
  "kishanganj-bihar","kotwa-bihar","lakhisarai-bihar","lala-bhadsara-bo-bihar",
  "lalganj-bo-bihar","lauriya-bihar","madanpur-bo-bihar","madhepura-collectorate-bihar",
  "madhubani-bihar","madhubanighat-bo-bihar","maharajganj-bihar","maheshkhunt-bihar",
  "mairwa-bihar","makhdumpur-bihar","maner-so-bihar","manihari-bihar",
  "masaurhi-bihar","masrakh-bihar","matihani-bo-bihar","mehsi-bihar",
  "mohania-bihar","mokama-chowk-so-bihar","motihari-court-bihar","munger-ho-bihar",
  "muriyar-bo-bihar","muzaffarpur-court-bihar","nalanda-bihar","nanpur-bihar",
  "nasriganj-bihar","naubatpur-bihar","naugachia-bihar","nautan-dubey-bihar",
  "nawada-ben-bihar","pakaria-bo-bihar","paliganj-so-bihar","parasia-bihar",
  "paroo-bihar","patahi-muzaffarpur-bihar","patna-gpo-ndc-bihar","patori-bo-bihar",
  "piprarhi-bihar","rafiganj-bihar","raghopur-bihar","rampur-bihar",
  "raxaul-bihar","rohtas-bihar","sahar-bhojpur-bihar","saharsa-bazar-bihar",
  "sahebganj-bihar","sahebpur-kamal-bihar","salempur-bihar","samastipur-ho-bihar",
  "sarangpur-bo-bihar","sasaram-local-board-bihar","semapur-factory-bihar","sheikhpura-bazar-bihar",
  "sheohar-bihar","sherghati-bihar","simri-bakhtiarpur-bihar","simri-dhamni-bo-bihar",
  "sitamarhi-ho-bihar","siwan-chowk-bazar-bihar","sultanganj-bhagalpur-bihar","supaul-bo-bihar",
  "tariama-bo-bihar","tekari-bihar","turkaulia-bihar","vaishali-bihar",
  "west-lohia-nagar-bihar","ambikapur-nyalaya-chattisgarh","balod-chattisgarh","baloda-bazar-chattisgarh",
  "balrampur-chattisgarh","banda-chattisgarh","bangaon-chattisgarh","bastarbudra-chattisgarh",
  "bemetara-chattisgarh","bharatpur-chattisgarh","bhatapara-chattisgarh","bilaspur-kutchery-bilaspurcgh-chattisgarh",
  "borigaon-chattisgarh","chikhli-chattisgarh","dalla-chattisgarh","dantewada-so-chattisgarh",
  "dhamtari-chattisgarh","durgapur-bo-chattisgarh","durgapur-chattisgarh","jagdalpur-sadar-bzr-so-chattisgarh",
  "jaipur-chattisgarh","janjgiri-bo-chattisgarh","jashpur-bo-chattisgarh","kalyanpur-chattisgarh",
  "kanker-ho-chattisgarh","kolar-chattisgarh","kondagaon-naka-so-chattisgarh","korba-ho-chattisgarh",
  "krishnanagar-chattisgarh","kundla-chattisgarh","lanka-chattisgarh","mahasamund-chattisgarh",
  "mungeli-chattisgarh","narayanpur-so-narayanpur-chattisgarh","patna-chattisgarh","pratapgarh-chattisgarh",
  "puri-chattisgarh","raigarh-jute-mill-chattisgarh","raipur-rs-chattisgarh","rajim-chattisgarh",
  "rajnandgaon-stadium-chattisgarh","ramgarh-chattisgarh","rampur-chattisgarh","sambalpur-chattisgarh",
  "seoni-chattisgarh","shankarpur-chattisgarh","siltara-bo-chattisgarh","sitapur-chattisgarh",
  "sukma-so-chattisgarh","surajpur-chattisgarh","udaipur-chattisgarh","delhi",
  "shahdara-delhi","ahmedabad","amreli-j-p-gujarat","anand-bhankhri-gujarat",
  "ankleshwar-gujarat","bharuch-city-gujarat","bhavnagar-para-gujarat","bhuj-ravalwadi-gujarat",
  "bilimora-gujarat","borsad-gujarat","botad-gujarat","chhotaudepur-gujarat",
  "dadra-gujarat","dahod-ho-gujarat","daman-gujarat","devsar-gujarat",
  "dholka-gujarat","diu-gujarat","dwarka-gujarat","gandhidham-gujarat",
  "gandhinagar-sector-30-gujarat","gir-devli-bo-gujarat","godhra-gujarat","gondal-ram-dwar-nd-t-gujarat",
  "hajipur-gujarat","halol-gujarat","himatnagar-station-road-gujarat","jamnagar-ho-gujarat",
  "jetpur-gujarat","junagadh-agri-campus-gujarat","kachchh-mandvi-gujarat","kadi-gujarat",
  "kalol-ho-gujarat","kamrej-gujarat","keshod-gujarat","khambha-gujarat",
  "khambhat-gujarat","kheda-ho-gujarat","kundla-para-so-gujarat","mahesana-bazar-gujarat",
  "mahisa-gujarat","mahuvas-bo-gujarat","modasa-gujarat","morbi-mdg-gujarat",
  "nadiad-ho-gujarat","narmada-nagar-bharuch-gujarat","navsari-ho-gujarat","palanpur-hanuman-tekri-t-gujarat",
  "palitana-gujarat","patan-bo-gujarat","petlad-gujarat","porbandar-bhojeshwar-gujarat",
  "rajkot-raiya-road-gujarat","silvassa-gujarat","surat-ho-gujarat","surendranagar-udyognagar-gujarat",
  "unjha-gujarat","va-gujarat","vadodarazala-bo-gujarat","vapi-gujarat",
  "veraval-gujarat","visnagar-gujarat","vyara-gujarat","akbarpur-haryana",
  "ambala-city-kucthery-so-haryana","aurangabad-haryana","baraut-haryana","bhiwani-ho-haryana",
  "charkhi-dadri-city-haryana","faridabad","faridpur-haryana","fatehabad-fatehabad-haryana",
  "fatehpur-haryana","gohana-haryana","gurugram","hansi-haryana",
  "hata-haryana","hisar-kty-haryana","hodal-haryana","jalalpur-haryana",
  "jhajjar-haryana","jindran-bo-haryana","kaithal-so-haryana","kalka-rs-so-haryana",
  "kalpi-haryana","karad-haryana","karnal-new-prem-nagar-so-haryana","khatauli-haryana",
  "kurukshetra-ho-haryana","laharpur-haryana","madanpur-haryana","narnaul-city-haryana",
  "narsinghpur-haryana","nuh-haryana","palwal-haryana","panchkula-sector-12-so-haryana",
  "panipat-gt-road-so-haryana","ramgarh-haryana","rewari-haryana","rohtak-sector-i-haryana",
  "shahabadm-so-haryana","simla-haryana","sirsa-ho-haryana","sirsi-haryana",
  "sultanpur-haryana","udaipur-haryana","yamunanagar-ho-haryana","bilaspur-bo-himachal-pradesh",
  "chamba-ho-himachal-pradesh","hamirpur-ho-hp-circle-himachal-pradesh","kangra-town-bo-himachal-pradesh","kullu-ho-himachal-pradesh",
  "mandi-ho-himachal-pradesh","rampur-bo-himachal-pradesh","shimla-east-himachal-pradesh","sultanpur-himachal-pradesh",
  "tanda-himachal-pradesh","una-ho-himachal-pradesh","anantnag-city-jammu-kashmir","bandipora-jammu-kashmir",
  "baramulla-ho-jammu-kashmir","bhaderwah-jammu-kashmir","budgam-jammu-kashmir","devsar-bo-jammu-kashmir",
  "dodaj-bo-jammu-kashmir","ganderbal-jammu-kashmir","jammu-cantt-jammu-kashmir","kargil-so-jammu-kashmir",
  "kathua-ho-jammu-kashmir","kishtwar-jammu-kashmir","kralpora-jammu-kashmir","kulgam-jammu-kashmir",
  "kupwara-so-jammu-kashmir","lehar-bo-jammu-kashmir","pampore-jammu-kashmir","poonch-jammu-kashmir",
  "pulwama-jammu-kashmir","puranatulail-jammu-kashmir","rajouri-ho-jammu-kashmir","ramban-jammu-kashmir",
  "rangreth-jammu-kashmir","reasi-jammu-kashmir","samba-jammu-kashmir","shopian-jammu-kashmir",
  "srinagar-gpo-jammu-kashmir","tral-jammu-kashmir","udhampur-ho-jammu-kashmir","bari-jharkhand",
  "bhurkunda-jharkhand","bilaspur-jharkhand","bokaro-steel-city-ho-jharkhand","chaibasa-ho-jharkhand",
  "chakradharpur-jharkhand","chandrapura-jharkhand","chatra-jharkhand","chhatarpur-jharkhand",
  "deoghar-college-jharkhand","dhanbad-bazar-jharkhand","dumka-ho-jharkhand","gamharia-jharkhand",
  "garhwa-jharkhand","giridih-town-jharkhand","godda-jharkhand","gumla-ho-jharkhand",
  "hazaribagh-ho-jharkhand","jaipur-jharkhand","jamshedpur-ho-jharkhand","jamtara-jharkhand",
  "kalyanpur-jharkhand","kathara-jharkhand","khunti-jharkhand","kodarma-jharkhand",
  "kundla-jharkhand","latehar-rs-jharkhand","lohardaga-jharkhand","madhuban-jharkhand",
  "madhupur-jharkhand","matihani-jharkhand","pakur-jharkhand","palamu-bo-jharkhand",
  "phusro-bazar-jharkhand","rajmahal-jharkhand","ramgarh-jharkhand","rampur-jharkhand",
  "ranchi-airport-jharkhand","sagar-jharkhand","sahibganj-jharkhand","shankarpur-jharkhand",
  "simdega-jharkhand","sirsi-jharkhand","bagalkot-uhs-campus-so-karnataka","balla-karnataka",
  "bangalore","belagavi-karnataka","bengaluru-city-so-karnataka","bhadravathi-jannapura-so-karnataka",
  "bhatkal-bazar-so-karnataka","bidari-karnataka","challakere-bazar-so-karnataka","chamarajanagara-bazar-karnataka",
  "chikkamagaluru-fort-so-karnataka","chintamani-so-karnataka","chitradurga-dist-office-so-karnataka","dharwad-farm-karnataka",
  "firozabad-karnataka","gadag-betgeri-so-karnataka","gaddankeri-karnataka","gandhinagar-karnataka",
  "gangavathi-ars-karnataka","gokak-college-road-so-karnataka","hansi-karnataka","harihara-karnataka",
  "hassandahalli-karnataka","haveri-bs-so-karnataka","hosapete-karnataka","hosur-karnataka",
  "ilkal-so-karnataka","islampur-karnataka","jaigaon-karnataka","jalalpur-karnataka",
  "jigani-so-karnataka","kalaburagi-ho-karnataka","kannur-karnataka","karur-karnataka",
  "karwar-baitkhol-so-karnataka","kod-karnataka","kolar-gulpet-karnataka","koppa-karnataka",
  "koppal-g-s-gunj-so-karnataka","kota-karnataka","kunda-karnataka","kundapura-market-karnataka",
  "malegaon-karnataka","malkapur-karnataka","mandya-district-so-karnataka","mangaluru-karnataka",
  "mehkar-karnataka","mirzapur-karnataka","mysuru-fort-so-karnataka","puttur-bo-karnataka",
  "raichur-uas-so-karnataka","ramanagaram-so-karnataka","rampur-karnataka","ranebennur-bzr-so-karnataka",
  "rudrapur-karnataka","seoni-karnataka","shivamogga-doddapete-so-karnataka","shorapur-so-karnataka",
  "sindhanur-court-complex-karnataka","sirsi-market-so-karnataka","siruguppa-sadashivanagar-so-karnataka","sultanpur-karnataka",
  "taranagar-karnataka","tumakuru-karnataka","tumkur-karnataka","udupi-courts-karnataka",
  "vaddu-karnataka","vijayapura-kutchery-karnataka","yadgiri-town-so-karnataka","alappuzha-iron-bridge-kerala",
  "attingal-ho-kerala","ernakulam-college-kerala","idukki-colony-kerala","irinjalakuda-mkt-kerala",
  "kalpetta-ho-kerala","kanhangad-ho-kerala","kannur-government-medical-college-kerala","kasaragod-ho-kerala",
  "kochi-airport-kerala","kollam-kerala","kothamangalam-ernakulam-kerala","kottayam-malabar-bo-kerala",
  "kozhikode-parcel-centre-kerala","malappuram-ho-kerala","mannarkkad-kerala","muvattupuzha-bazar-bo-kerala",
  "nilambur-kerala","ottapalam-ho-kerala","palakkad-industrial-estate-bo-kerala","pathanamthitta-ho-kerala",
  "pattambi-kerala","payyanur-kerala","punalur-paper-mills-kerala","tali-kerala",
  "tanurmbr-kerala","thalassery-bo-kerala","thiruvananthapuram-chalai-kerala","thodupuzha-ho-kerala",
  "thrissur-engg-college-kerala","vaikom-thekkenada-bo-kerala","venjaramoodu-kerala","achalpur-madhya-pradesh",
  "agar-malwa-so-madhya-pradesh","agra-madhya-pradesh","ahmadpur-madhya-pradesh","akola-madhya-pradesh",
  "alirajpur-so-madhya-pradesh","amarpur-madhya-pradesh","amba-madhya-pradesh","anu-madhya-pradesh",
  "ashoknagar-city-so-madhya-pradesh","atri-madhya-pradesh","bahadurpur-madhya-pradesh","balaghat-ho-madhya-pradesh",
  "ballarpur-madhya-pradesh","bangaon-madhya-pradesh","banjari-madhya-pradesh","banka-madhya-pradesh",
  "baran-madhya-pradesh","bari-madhya-pradesh","barwani-so-madhya-pradesh","beed-madhya-pradesh",
  "betul-ganj-so-madhya-pradesh","bharatpur-madhya-pradesh","bhind-ho-madhya-pradesh","bhopal-gpo-madhya-pradesh",
  "biaora-so-madhya-pradesh","bilaspur-madhya-pradesh","birpur-madhya-pradesh","burhanpur-rajpura-so-madhya-pradesh",
  "chandpur-madhya-pradesh","chandrapur-madhya-pradesh","chandrapura-madhya-pradesh","chhapra-madhya-pradesh",
  "chhatarpur-madhya-pradesh","chhindwara-ho-madhya-pradesh","chikhli-madhya-pradesh","dabraimalia-madhya-pradesh",
  "dahod-madhya-pradesh","damoh-madhya-pradesh","datia-rsi-madhya-pradesh","dehri-madhya-pradesh",
  "dewas-madhya-pradesh","dhari-madhya-pradesh","dindori-so-dindori-madhya-pradesh","durgapur-madhya-pradesh",
  "fatehpur-madhya-pradesh","gadar-madhya-pradesh","garhwa-madhya-pradesh","gohana-madhya-pradesh",
  "gonda-madhya-pradesh","gopalganj-madhya-pradesh","gorakhpur-madhya-pradesh","guna-madhya-pradesh",
  "gwaliorkalan-madhya-pradesh","hamirpur-madhya-pradesh","handia-madhya-pradesh","harda-khurd-madhya-pradesh",
  "hata-madhya-pradesh","hoshangabad-city-so-madhya-pradesh","indore","itarsi-so-madhya-pradesh",
  "jabalpur-factory-so-madhya-pradesh","jalalpur-madhya-pradesh","jalandhar-madhya-pradesh","jalna-madhya-pradesh",
  "jamui-madhya-pradesh","jetpur-madhya-pradesh","jhabua-collectorate-so-madhya-pradesh","jhansi-madhya-pradesh",
  "jodhpur-madhya-pradesh","joura-madhya-pradesh","kalpi-madhya-pradesh","kalyanpur-madhya-pradesh",
  "kanth-madhya-pradesh","katni-madhav-nagar-so-madhya-pradesh","khandwa-madhya-pradesh","kharagpur-madhya-pradesh",
  "khargone-ho-madhya-pradesh","kishanganj-madhya-pradesh","kota-madhya-pradesh","kotwa-madhya-pradesh",
  "kunda-madhya-pradesh","kundla-madhya-pradesh","laharpur-madhya-pradesh","lalitpur-madhya-pradesh",
  "madanpur-madhya-pradesh","maharajganj-madhya-pradesh","maihar-so-madhya-pradesh","mainpuri-madhya-pradesh",
  "malegaon-madhya-pradesh","mand-madhya-pradesh","mandla-madhya-pradesh","mau-madhya-pradesh",
  "mirzapur-madhya-pradesh","mohania-madhya-pradesh","morena-ho-madhya-pradesh","nagda-madhya-pradesh",
  "nanded-madhya-pradesh","nanpur-madhya-pradesh","narsinghpura-madhya-pradesh","neemuch-city-so-madhya-pradesh",
  "pali-madhya-pradesh","panna-naka-chhatarpur-so-madhya-pradesh","parasia-so-madhya-pradesh","parli-madhya-pradesh",
  "patan-madhya-pradesh","patna-madhya-pradesh","patori-madhya-pradesh","pipariya-madhya-pradesh",
  "pithampur-so-madhya-pradesh","porsa-so-madhya-pradesh","pratapgarh-madhya-pradesh","raghunathpur-madhya-pradesh",
  "rai-madhya-pradesh","raipur-madhya-pradesh","rajgarh-madhya-pradesh","rajpura-madhya-pradesh",
  "ramgarh-madhya-pradesh","rampur-madhya-pradesh","ratlam-city-so-madhya-pradesh","rewai-madhya-pradesh",
  "sabalgarh-so-madhya-pradesh","sagar-madhya-pradesh","satna-jawahar-nagar-so-madhya-pradesh","sehore-madhya-pradesh",
  "sendhwal-madhya-pradesh","seoni-madhya-pradesh","shah-madhya-pradesh","shahpura-madhya-pradesh",
  "shajapur-town-so-madhya-pradesh","shankarpur-madhya-pradesh","sheikhpura-madhya-pradesh","sheopur-so-madhya-pradesh",
  "shivpur-madhya-pradesh","sidhi-madhya-pradesh","singrauli-rs-madhya-pradesh","sirsa-madhya-pradesh",
  "sirsi-madhya-pradesh","sitapur-madhya-pradesh","srinagar-madhya-pradesh","sultanganj-madhya-pradesh",
  "sultanpur-madhya-pradesh","tanda-madhya-pradesh","tikamgarh-ho-madhya-pradesh","udaipur-madhya-pradesh",
  "ujjain-kothi-so-madhya-pradesh","umaria-madhya-pradesh","vidisha-mandi-so-madhya-pradesh","waidhan-so-madhya-pradesh",
  "wardha-madhya-pradesh","achalpur-city-so-maharashtra","ahmednagar-city-so-maharashtra","akola-maharashtra",
  "akot-maharashtra","ali-maharashtra","amalner-so-jalgaon-maharashtra","amba-maharashtra",
  "ambala-maharashtra","amravati-ho-maharashtra","arani-maharashtra","atri-maharashtra",
  "ballarpur-maharashtra","bangaon-maharashtra","bansi-maharashtra","baramati-court-so-maharashtra",
  "bari-maharashtra","barshi-so-maharashtra","basmathnagar-so-maharashtra","beed-maharashtra",
  "betul-maharashtra","bhandara-road-so-maharashtra","bhiwadi-maharashtra","bhuj-maharashtra",
  "bhusawal-kutchery-so-maharashtra","boisar-so-maharashtra","borigaon-maharashtra","chakan-so-maharashtra",
  "chalisgaon-town-so-maharashtra","chandrapur-ho-maharashtra","chikhli-maharashtra","chiplun-ho-maharashtra",
  "chittaranjan-maharashtra","chopda-so-maharashtra","dhar-maharashtra","dharmapuri-maharashtra",
  "dhule-pramod-nagar-so-maharashtra","dolvi-bo-maharashtra","durgapur-maharashtra","gadchiroli-so-maharashtra",
  "gondia-bazar-so-maharashtra","guntur-maharashtra","hata-maharashtra","hinganghat-so-maharashtra",
  "hingoli-so-maharashtra","hosur-maharashtra","ichalkaranji-ho-maharashtra","indore-maharashtra",
  "islampur-maharashtra","jaigaon-maharashtra","jainagar-maharashtra","jaipur-maharashtra",
  "jalalpur-maharashtra","jalgaon-maharashtra","jalna-railway-station-so-maharashtra","jaysingpur-so-maharashtra",
  "kalyan-maharashtra","karadgaon-maharashtra","karanja-maharashtra","karnal-maharashtra",
  "khamgaon-maharashtra","kolhapur-rs-so-maharashtra","latur-rs-so-maharashtra","lonavala-bazar-so-maharashtra",
  "majal-maharashtra","malegaon-maharashtra","malkapur-maharashtra","mehkar-so-maharashtra",
  "mubarakpur-maharashtra","mumbai","nagaon-maharashtra","nagda-maharashtra",
  "nagpura-maharashtra","nand-maharashtra","nanded-maharashtra","nashik-city-so-maharashtra",
  "osmanabad-town-maharashtra","pachorabari-maharashtra","palghar-ho-maharashtra","pali-maharashtra",
  "pandharpur-ho-maharashtra","panvel-ho-maharashtra","parbhani-town-so-maharashtra","parli-tps-so-maharashtra",
  "patan-maharashtra","pipariya-maharashtra","pratapgarh-maharashtra","pune",
  "puri-maharashtra","pusad-so-maharashtra","rai-maharashtra","raipur-maharashtra",
  "ramgarh-maharashtra","rampur-maharashtra","ratnagiri-collectorate-so-maharashtra","salem-maharashtra",
  "sangamner-maharashtra","sangli-city-so-maharashtra","satara-maharashtra","satarda-so-maharashtra",
  "seoni-maharashtra","shaha-maharashtra","shahapur-maharashtra","shankarpur-maharashtra",
  "shegaon-maharashtra","shirpur-maharashtra","sindhudurgnagari-mdg-so-maharashtra","sinnar-so-maharashtra",
  "sultanpur-maharashtra","talegaon-maharashtra","tanda-maharashtra","tekari-maharashtra",
  "thanepada-maharashtra","udgirganj-so-maharashtra","uran-so-maharashtra","vasai-road-e-so-maharashtra",
  "waladgaon-maharashtra","wani-maharashtra","war-maharashtra","washim-so-maharashtra",
  "yavatmal-town-so-maharashtra","agartala-bazar-so-north-eastern","ai-north-eastern","along-so-north-eastern",
  "ampati-so-north-eastern","baghmara-so-north-eastern","balurghat-north-eastern","belonia-aerodrome-north-eastern",
  "bishnupur-north-eastern","bomdila-so-north-eastern","champhai-so-north-eastern","chandel-so-north-eastern",
  "changlang-so-north-eastern","churachandpur-so-north-eastern","daporijo-so-north-eastern","deomali-so-north-eastern",
  "dimapur-bazar-so-north-eastern","durgapur-north-eastern","imphal-ho-north-eastern","itanagar-ho-north-eastern",
  "jaipur-north-eastern","jiribam-bazar-so-north-eastern","jowai-mdg-north-eastern","kadi-north-eastern",
  "kailashahar-so-north-eastern","kakching-lamkhai-north-eastern","kangpokpi-mission-north-eastern","khliehriat-so-north-eastern",
  "khowai-court-so-north-eastern","kiphire-so-north-eastern","kohima-science-college-so-north-eastern","kolasib-so-north-eastern",
  "koloriang-north-eastern","krishnanagar-north-eastern","lanka-north-eastern","lawngtlai-so-north-eastern",
  "likabali-so-north-eastern","lohitpur-north-eastern","longleng-so-north-eastern","lung-north-eastern",
  "madhuban-north-eastern","madhupur-north-eastern","mamit-so-north-eastern","mawkyrwat-so-north-eastern",
  "mokokchung-so-north-eastern","mongkholemba-so-north-eastern","na-north-eastern","namchik-north-eastern",
  "nongpoh-so-north-eastern","nongstoin-so-north-eastern","north-padmabil-north-eastern","pasighat-so-north-eastern",
  "peren-so-north-eastern","phek-so-north-eastern","pherzawl-north-eastern","resubelpara-so-north-eastern",
  "roing-north-eastern","saiha-so-north-eastern","senapati-so-north-eastern","sepahijala-north-eastern",
  "seppa-so-north-eastern","serchhip-so-north-eastern","shillong-gpo-north-eastern","srinagar-north-eastern",
  "tamenglong-khunjao-north-eastern","taranagar-north-eastern","tawang-so-north-eastern","tengnoupal-north-eastern",
  "thoubal-leisangthem-north-eastern","tuensang-village-north-eastern","tura-ho-north-eastern","udaipur-north-eastern",
  "ukhrul-so-north-eastern","west-laxmibill-north-eastern","wokha-village-north-eastern","yingkiong-so-north-eastern",
  "ziro-so-north-eastern","zunheboto-so-north-eastern","anantapur-odisha","angulai-odisha",
  "baghua-odisha","bala-odisha","balia-odisha","banda-odisha",
  "banjari-odisha","bargarh-bargaon-odisha","bari-odisha","baripada-court-so-odisha",
  "benipur-odisha","bhadrak-banka-bazar-so-odisha","bharatpur-odisha","bhawanipatna-ho-odisha",
  "bhubaneswar-court-so-odisha","bilaspur-odisha","borigaon-odisha","boudh-court-so-odisha",
  "brahmapura-odisha","chakradharpur-odisha","chandpur-odisha","chandrapur-odisha",
  "choudwar-bazar-so-odisha","cuttack-gpo-odisha","dankuni-odisha","dhenkanal-ho-odisha",
  "durgapur-odisha","ekma-odisha","fatehpur-odisha","ganjam-so-odisha",
  "gondal-odisha","gorakhpur-odisha","hajipur-odisha","hamirpur-odisha",
  "jagatsinghpur-ho-odisha","jagdalpur-odisha","jaipur-odisha","jajpur-ho-odisha",
  "jeyporek-ho-odisha","jharsuguda-ho-odisha","kalyanpur-odisha","kamarda-odisha",
  "kanpur-odisha","karanja-odisha","kendrapara-ho-odisha","keonjhar-odisha",
  "koraput-collectorate-so-odisha","krishnanagar-odisha","madanpur-odisha","madhuban-odisha",
  "madhupur-odisha","malda-odisha","malkangiri-colony-so-odisha","mathura-odisha",
  "medinipur-odisha","mirzapur-odisha","nabarangpur-bazar-so-odisha","nagaon-odisha",
  "narsinghpur-odisha","nayagarh-bazar-so-odisha","nuapada-odisha","pandua-odisha",
  "para-odisha","patna-odisha","pratapgarh-odisha","puri-station-road-so-odisha",
  "raghunathpur-odisha","raipur-odisha","rairangpur-odisha","rajgangpur-so-odisha",
  "ramgarh-odisha","rampur-odisha","ratnagiri-odisha","rayagada-college-so-odisha",
  "rourkela---2-so-odisha","rudrapur-odisha","sagar-odisha","sahaspur-odisha",
  "sambalpur-ho-odisha","shankarpur-odisha","simla-odisha","subarnapur-odisha",
  "sultanpur-odisha","sundargarh-ho-odisha","tanda-odisha","tundla-odisha",
  "abohar-punjab","amritsar-gpo-punjab","barnala-punjab","batala-ho-punjab",
  "bathinda-cantt-punjab","faridkot-ho-punjab","fatehgarh-sahib-punjab","fazilka-punjab",
  "gurdaspur-ho-punjab","hajipur-punjab","hoshiarpur-city-punjab","jagraon-ho-punjab",
  "jalalabad-bo-punjab","jalandhar-cantt-ho-punjab","kapurthala-town-punjab","khanna-ho-punjab",
  "kotkapura-punjab","ludhiana-kty-punjab","malerkotla-punjab","mandi-ladhuka-bo-punjab",
  "mansa-mansa-punjab","moga-ho-punjab","muktsar-kty-punjab","nabha-punjab",
  "pathankot-punjab","patiala-city-punjab","phagwara-ho-punjab","raipur-punjab",
  "rajpura-bo-punjab","sangrur-ho-punjab","sekhu-bo-punjab","sri-muktsar-sahib-mdg-punjab",
  "tandaura-bo-punjab","tarn-taran-ho-punjab","achalpur-rajasthan","agra-rajasthan",
  "ajmer-ho-rajasthan","akbarpur-rajasthan","akola-rajasthan","alwar-bus-stand-so-rajasthan",
  "balotra-ia-so-rajasthan","banda-rajasthan","bandikui-rajasthan","banjari-rajasthan",
  "bansi-rajasthan","banswara-ho-rajasthan","baran-rajasthan","bari-rajasthan",
  "barmer-pr-so-rajasthan","bayana-rajasthan","beawar-raj-ho-rajasthan","bhandara-rajasthan",
  "bhara-rajasthan","bhilwara-ho-rajasthan","bikaner-city-so-rajasthan","bilaspur-rajasthan",
  "bisalpur-rajasthan","bundi-ho-rajasthan","chandpur-rajasthan","chittorgarh-fort-rajasthan",
  "chomu-rajasthan","churu-collectorate-so-rajasthan","da-rajasthan","deoria-rajasthan",
  "dewas-rajasthan","dhar-rajasthan","dhol-rajasthan","dungarpur-bo-rajasthan",
  "fatehpur-rajasthan","fatehpur-shekhawati-rajasthan","gangashahar-so-rajasthan","gohana-rajasthan",
  "hamirpur-rajasthan","hanumangarh-town-bazar-so-rajasthan","hindaun-city-rajasthan","jainagar-rajasthan",
  "jaipur","jaisalmer-bsf-rajasthan","jalalpur-rajasthan","jalore-ho-rajasthan",
  "jetpur-rajasthan","jhalawar-ho-rajasthan","jhunjhunu-city-so-rajasthan","jodhpura-rajasthan",
  "kalyanpur-rajasthan","kanau-rajasthan","kanpur-rajasthan","karauli-rajasthan",
  "khandwa-rajasthan","kolar-rajasthan","kota-jn-so-rajasthan","kotputli-rajasthan",
  "kuchamancity-so-rajasthan","kunda-rajasthan","kundla-rajasthan","m-rajasthan",
  "mandla-rajasthan","manihari-rajasthan","mau-rajasthan","nagaurcity-so-rajasthan",
  "neembali-rajasthan","nokhara-rajasthan","pali-rajasthan","parli-rajasthan",
  "patan-rajasthan","patna-rajasthan","phalodi-rajasthan","pilani-so-rajasthan",
  "pusad-rajasthan","raipur-rajasthan","rajkot-rajasthan","rajmahal-rajasthan",
  "rajpura-rajasthan","rajsamand-so-rajasthan","ramganj-rajasthan","ramgarh-rajasthan",
  "road-no-5-vkia-so-rajasthan","saharanpur-rajasthan","sandila-rajasthan","sawaimadhopur-bazar-rajasthan",
  "shahpura-rajasthan","sheopur-rajasthan","sikarpura-bo-rajasthan","simla-rajasthan",
  "sirohi-rajasthan","srinagar-rajasthan","sujangarh-so-rajasthan","suratgarh-rajasthan",
  "taranagar-so-rajasthan","tonkra-rajasthan","udaipuria-bo-rajasthan","vijayapura-rajasthan",
  "chennai","ambasamudram-ho-tamilnadu","ambur-so-tamilnadu","arakkonam-ho-tamilnadu",
  "ariyalur-tamilnadu","chennai-gpo-tamilnadu","chidambaram-cutcherry-so-tamilnadu","chittoor-tamilnadu",
  "coimbatore-ho-tamilnadu","colachel-so-tamilnadu","coonoor-rs-so-tamilnadu","cuddalore-court-buildings-so-tamilnadu",
  "cumbum-so-theni-tamilnadu","dharmapuri-tamilnadu","dindigul-collectorate-tamilnadu","erode-collectorate-tamilnadu",
  "gandhinagar-tamilnadu","gobichettipalayam-tamilnadu","gummidipundi-tamilnadu","hosur-so-dharmapuri-tamilnadu",
  "kanchipuram-collectorate-so-tamilnadu","kanniyakumari-so-tamilnadu","kannur-tamilnadu","karai-tamilnadu",
  "karaikudi-uthstreet-so-tamilnadu","karur-ho-tamilnadu","kattumannarkoil-so-tamilnadu","kothamangalam-tamilnadu",
  "kovilpatti-ind-estate-tamilnadu","krishnagiri-project-so-tamilnadu","kumbakonam-ho-tamilnadu","madur-tamilnadu",
  "mahendramangalam-tamilnadu","mangalagiri-tamilnadu","mannargudi-ho-tamilnadu","mayiladuthurai-cutchery-so-tamilnadu",
  "mettur-tamilnadu","nagapattinam-ho-tamilnadu","nagercoil-bazaar-so-tamilnadu","namakkal-bazaar-so-tamilnadu",
  "padmanabhapuram-fort-so-tamilnadu","palani-ho-tamilnadu","pali-tamilnadu","panruti-tamilnadu",
  "perambalur-tamilnadu","pollachi-west-tamilnadu","pudukkottai-vaiyampatti-tamilnadu","rajapalayam-tamilnadu",
  "ramanathapuram-tamilnadu","ranipet-industrial-estate-tamilnadu","salem-north-so-tamilnadu","sivaganga-courts-tamilnadu",
  "sivakasi-east-tamilnadu","tenkasi-ho-tamilnadu","thalaiyuthu-bo-tamilnadu","thanjavur-city-so-tamilnadu",
  "theni-so-tamilnadu","tindivanam-ho-tamilnadu","tiruchengodu-uth-so-tamilnadu","tiruchirappalli-townhall-tamilnadu",
  "tirunelveli-pettai-tamilnadu","tirupattur-tamilnadu","tiruppur-tamilnadu","tiruvallur-ho-tamilnadu",
  "tiruvannamalai-ho-tamilnadu","tiruvarur-north-so-tamilnadu","tuticorin-cathedral-so-tamilnadu","vadalur-so-tamilnadu",
  "vaniyambadi-rs-tamilnadu","vellore-tamilnadu","villukuri-so-tamilnadu","viluppuram-ho-tamilnadu",
  "virudhunagar-bus-stand-tamilnadu","adilabad-ho-telangana","ambala-telangana","asifabad-so-telangana",
  "bhimavaram-telangana","bhongir-ho-telangana","bodhan-so-telangana","burhanpur-telangana",
  "dharmavaram-telangana","dindigul-telangana","faizabad-telangana","gadwal-ho-telangana",
  "gandhinagar-telangana","ghatkesar-so-telangana","gudivada-telangana","hajipur-telangana",
  "hindupur-telangana","hyderabad","islampur-telangana","jagtial-ho-telangana",
  "jaipur-telangana","jalalpur-telangana","jangaon-telangana","kamareddy-ho-telangana",
  "kannur-telangana","karimnagar-ho-telangana","karur-telangana","khammampally-telangana",
  "kothagudem-telangana","krishnanagar-telangana","mahabubabad-ho-telangana","mahabubnagar-ho-telangana",
  "malkapur-telangana","mancherial-ho-telangana","medak-ho-telangana","medchal-so-telangana",
  "miryala-telangana","mirzapur-telangana","mubarakpur-telangana","nagarkurnool-so-telangana",
  "nalgonda-ho-telangana","narasapuram-telangana","nirmal-telangana","nizamabad-telangana",
  "peddapalli-ho-telangana","proddatur-telangana","rajannagudem-telangana","ramagundam-so-telangana",
  "rampur-telangana","rangareddy-district-court-so-telangana","ratnagiri-telangana","saidpur-telangana",
  "sangareddy-ho-telangana","siddipet-ho-telangana","sirsa-telangana","srinagar-telangana",
  "sultanpur-telangana","suryapet-ho-telangana","tandur-telangana","tanur-telangana",
  "vikarabad-ho-telangana","wanaparthy-telangana","warangal-ho-telangana","zaheerabad-ho-telangana",
  "agra-fort-ho-uttar-pradesh","akbarpur-uttar-pradesh","akola-uttar-pradesh","aligarh-dairy-farm-so-uttar-pradesh",
  "amethi-ho-uttar-pradesh","amroha-shahi-chabutra-uttar-pradesh","anand-nagar-uttar-pradesh","anpara-tps-uttar-pradesh",
  "aonla-uttar-pradesh","auraiya-ho-uttar-pradesh","azamgarh-city-uttar-pradesh","baghpat-uttar-pradesh",
  "baheri-uttar-pradesh","bahraicha-bo-uttar-pradesh","ballia-uttar-pradesh","balrampur-degree-college-uttar-pradesh",
  "banda-ho-uttar-pradesh","bansi-bo-uttar-pradesh","bara-uttar-pradesh","baraut-uttar-pradesh",
  "bareilly-ho-uttar-pradesh","basti-bs-uttar-pradesh","bhadohi-uttar-pradesh","bhagalpur-uttar-pradesh",
  "bhinga-uttar-pradesh","bijnor-ho-uttar-pradesh","bisalpur-uttar-pradesh","biswan-uttar-pradesh",
  "budaun-city-uttar-pradesh","bulandshahr-kutchery-uttar-pradesh","chakia-uttar-pradesh","chandauli-uttar-pradesh",
  "chandausi-uttar-pradesh","chandpur-uttar-pradesh","chauri-chaura-so-uttar-pradesh","chhibramau-uttar-pradesh",
  "chitrauli-bo-uttar-pradesh","chunar-uttar-pradesh","colonelganj-gonda-uttar-pradesh","dalla-uttar-pradesh",
  "deoband-uttar-pradesh","deoria-mubarakpur-bo-uttar-pradesh","dhampur-tehsil-so-uttar-pradesh","etah-ho-uttar-pradesh",
  "etawah-kutchery-uttar-pradesh","faizabad-ho-uttar-pradesh","faridpur-uttar-pradesh","farrukhabad-uttar-pradesh",
  "fatehabad-uttar-pradesh","fatehpur-vishnoi-bo-uttar-pradesh","firozabad-bazar-bo-uttar-pradesh","gaighat-uttar-pradesh",
  "gajraula-uttar-pradesh","ghaziabad","ghazipur-bo-uttar-pradesh","gola-gokaran-nath-uttar-pradesh",
  "gonda-uttar-pradesh","gorakhpur-ho-uttar-pradesh","gyanpur-uttar-pradesh","hamirpur-bo-uttar-pradesh",
  "handia-uttar-pradesh","hapur-mandi-uttar-pradesh","hardoi-uttar-pradesh","hata-uttar-pradesh",
  "hathras-uttar-pradesh","iltifatganj-uttar-pradesh","jalalpur-uttar-pradesh","jalaun-uttar-pradesh",
  "jaunpur-kty-uttar-pradesh","jhansi-cantt-uttar-pradesh","kaimganj-uttar-pradesh","kairana-uttar-pradesh",
  "kalpi-uttar-pradesh","kannauj-uttar-pradesh","kanpur-court-uttar-pradesh","kanth-uttar-pradesh",
  "kasganj-uttar-pradesh","kaushambi-uttar-pradesh","kerakat-uttar-pradesh","khaga-uttar-pradesh",
  "khalilabad-uttar-pradesh","khandwa-uttar-pradesh","khanna-uttar-pradesh","khatauli-uttar-pradesh",
  "kheri-rangdhang-bo-uttar-pradesh","khurja-mdg-uttar-pradesh","kosi-kalan-uttar-pradesh","kotwali-bijnor-uttar-pradesh",
  "krishnanagar-uttar-pradesh","kunda-uttar-pradesh","kushinagar-uttar-pradesh","laharpur-uttar-pradesh",
  "lakhimpur-uttar-pradesh","lalganj-uttar-pradesh","lalitpur-bo-uttar-pradesh","lanka-uttar-pradesh",
  "lucknow-chowk-ho-uttar-pradesh","madanpur-uttar-pradesh","maharajganj-uttar-pradesh","mahoba-uttar-pradesh",
  "mahrajganj-bo-uttar-pradesh","mainpuri-ho-uttar-pradesh","maniar-uttar-pradesh","mathuranagar-bo-uttar-pradesh",
  "matihani-uttar-pradesh","maulagarh-bo-uttar-pradesh","mauranipur-uttar-pradesh","meerut-university-uttar-pradesh",
  "meja-road-uttar-pradesh","mirzapur-uttar-pradesh","mohammadabad-gohana-chowk-uttar-pradesh","moradabad-city-uttar-pradesh",
  "mubarakpur-uttar-pradesh","muhammadpur-bo-uttar-pradesh","muzaffarnagar-saini-bo-uttar-pradesh","najibabad-uttar-pradesh",
  "naugarh-uttar-pradesh","nautanwa-bazar-so-uttar-pradesh","nawabganj-ho-uttar-pradesh","nizamabad-uttar-pradesh",
  "noida","orai-town-uttar-pradesh","padra-uttar-pradesh","phaphamau-uttar-pradesh",
  "pilibhit-ho-uttar-pradesh","pratapgarh-ho-uttar-pradesh","prayagraj-fort-so-uttar-pradesh","pukhrayan-uttar-pradesh",
  "raghunathpur-uttar-pradesh","rampur-uttar-pradesh","rasra-town-uttar-pradesh","rath-uttar-pradesh",
  "renukoot-uttar-pradesh","robertsganj-ho-uttar-pradesh","rudrapur-uttar-pradesh","saharanpur-ho-uttar-pradesh",
  "sahaspuri-bo-uttar-pradesh","sahaswan-uttar-pradesh","sahebganj-uttar-pradesh","sahjanwa-bo-uttar-pradesh",
  "saidabad-uttar-pradesh","saidpur-bo-uttar-pradesh","salempur-bo-uttar-pradesh","sambhal-uttar-pradesh",
  "sandila-uttar-pradesh","sarain-bo-uttar-pradesh","seohara-uttar-pradesh","shahganj-uttar-pradesh",
  "shahjahanpur-bo-uttar-pradesh","shamli-uttar-pradesh","shankarpur-uttar-pradesh","sherkot-uttar-pradesh",
  "shikohabad-uttar-pradesh","sikandra-rao-uttar-pradesh","sikandra-uttar-pradesh","sirsa-uttar-pradesh",
  "sitapur-city-uttar-pradesh","sultanpur-uttar-pradesh","tamkuhi-uttar-pradesh","thakurdwara-uttar-pradesh",
  "tilhar-uttar-pradesh","tirwa-uttar-pradesh","tundla-uttar-pradesh","ujhani-uttar-pradesh",
  "unchahara-kala-bo-uttar-pradesh","unnao-ho-uttar-pradesh","varanasi-cantt-ho-uttar-pradesh","vrindavan-colony-uttar-pradesh",
  "almora-ho-uttarakhand","bageshwar-uttarakhand","chamoli-uttarakhand","champawat-uttarakhand",
  "dehradun-gpo-uttarakhand","haldwani-ho-uttarakhand","haridwar-uttarakhand","kotdwara-ho-uttarakhand",
  "nainital-kutchert-nainital-uttarakhand","pithoragarh-ho-uttarakhand","rishikesh-uttarakhand","roorkee-city-uttarakhand",
  "rudraprayag-uttarakhand","rudrapur-bo-uttarakhand","sultanpur-uttarakhand","tehri-ho-uttarakhand",
  "uttarkashi-uttarakhand","ahmadpur-west-bengal","alipurduar-west-bengal","amarshi-west-bengal",
  "arambagh-ho-west-bengal","badkulla-west-bengal","balurghat-ho-west-bengal","bangaon-north-24-parganas-west-bengal",
  "bankura-ho-west-bengal","basirhat-bazar-west-bengal","beldanga-west-bengal","berhampore-station-road-west-bengal",
  "bethuadahari-west-bengal","bolpur-west-bengal","brahmapur-west-bengal","canning-town-ferry-ghat-west-bengal",
  "chakdah-west-bengal","chamagram-bo-west-bengal","chandpara-west-bengal","chittaranjan-west-bengal",
  "contai-super-market-west-bengal","cooch-behar-bazar-west-bengal","dakshin-gopalnagar-bo-west-bengal","dankuni-west-bengal",
  "darjeeling-court-west-bengal","debandi-bo-west-bengal","deganga-west-bengal","dhupguri-west-bengal",
  "diamond-harbour-rs-west-bengal","dinhata-west-bengal","durgachak-west-bengal","durgapur-bo-west-bengal",
  "falakata-west-bengal","gandhinagar-west-bengal","gopalganj-west-bengal","habra-west-bengal",
  "hooghly-west-bengal","howrah-rs-west-bengal","islampur-bo-west-bengal","jaigaon-bo-west-bengal",
  "jalpaiguri-ho-west-bengal","jangalpara-bazar-bo-west-bengal","jhargram-ho-west-bengal","kakdwip-west-bengal",
  "kalimpong-mdg-west-bengal","kalna-west-bengal","kandi-ho-west-bengal","katwa-bazar-west-bengal",
  "khanakul-west-bengal","kharagpur-west-bengal","kolkata","krishnanagar-court-west-bengal",
  "maldanga-bo-west-bengal","mathura-west-bengal","medinipurgram-bo-west-bengal","mejia-th-power-station-west-bengal",
  "midnapore-ho-west-bengal","minakhan-bo-west-bengal","murshidabad-west-bengal","nadiara-bo-west-bengal",
  "northern-avenue-west-bengal","pandua-west-bengal","purulia-ho-west-bengal","raghunathpur-bo-west-bengal",
  "raiganj-town-west-bengal","rampur-west-bengal","rampurhat-ho-west-bengal","ranaghat-rupashreepally-bo-west-bengal",
  "saktipur-west-bengal","siliguri-bazar-west-bengal","simla-west-bengal","sitapur-west-bengal",
  "swarupnagar-west-bengal","tamluk-ho-west-bengal","tufanganj-west-bengal","udaipur-west-bengal"
];

const db = new Client({ connectionString: process.env.DATABASE_URL });
await db.connect();

const { rows: [before] } = await db.query(
  "SELECT COUNT(*) AS cnt FROM locations WHERE seo_priority = true"
);
console.log(`seo_priority before: ${before.cnt}`);

const BATCH = 200;
let totalTouched = 0;

for (let i = 0; i < PRIORITY_SLUGS.length; i += BATCH) {
  const batch = PRIORITY_SLUGS.slice(i, i + BATCH);
  const placeholders = batch.map((_, j) => `$${j + 1}`).join(", ");
  const result = await db.query(
    `UPDATE locations SET seo_priority = true WHERE is_active = true AND slug IN (${placeholders})`,
    batch
  );
  totalTouched += result.rowCount ?? 0;
  console.log(`  Batch ${Math.floor(i / BATCH) + 1}: updated ${result.rowCount} rows`);
}

const { rows: foundRows } = await db.query(
  `SELECT slug FROM locations WHERE is_active = true AND slug = ANY($1::text[])`,
  [PRIORITY_SLUGS]
);
const foundSet = new Set(foundRows.map((r: { slug: string }) => r.slug));
const missingSlug = PRIORITY_SLUGS.filter(s => !foundSet.has(s));

const { rows: [after] } = await db.query(
  "SELECT COUNT(*) AS cnt FROM locations WHERE seo_priority = true"
);

await db.end();

console.log(`
=== SEED COMPLETE ===`);
console.log(`DB rows touched: ${totalTouched}`);
console.log(`seo_priority before: ${before.cnt}  →  after: ${after.cnt}`);
console.log(`Authoritative slugs in DB: ${foundSet.size} / ${PRIORITY_SLUGS.length}`);

if (missingSlug.length > 0) {
  console.error(`
❌ ERROR: ${missingSlug.length} expected slug(s) not found as active locations:`);
  missingSlug.forEach(s => console.error(`   - ${s}`));
  process.exit(1);
}

console.log(`✅  All ${PRIORITY_SLUGS.length} slugs confirmed present.`);
console.log(`✅  ${after.cnt} total priority locations set — sitemap will show ${Math.ceil(Number(after.cnt) / 349)} pSEO files.`);
